name: YouTube M3U Güncelleyici

on:
  schedule:
    - cron: '0 */6 * * *' # Her 6 saatte bir otomatik çalışır
  workflow_dispatch:      # Manuel olarak başlatma butonu ekler

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Dosyayı geri yazabilmek için gerekli izin

    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Scripti Çalıştır
        run: python generate_m3u.py

      - name: Güncellemeleri Kaydet ve Gönder
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add metube.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Otomatik M3U Güncelleme: $(date)" && git push)
